
/*********************    Autogenerated file. DO NOT EDIT *******************
 * Generated from Arm ML Embedded Evaluation Kit (MLEK) project.
 * Script:          gen_utils.py
 * Original file:    * Date:            2025-01-08 20:49:18.286420
 ***************************************************************************/

#include "sample_files.h"
#include <stddef.h>

static const char* imgFilenames[] = {
    "dog.jpeg",
};

static const uint8_t* imgArrays[] = {
    im0
};

const char* get_sample_data_filename(const uint32_t idx)
{
    if (idx < NUMBER_OF_FILES) {
        return imgFilenames[idx];
    }
    return NULL;
}

const uint8_t* get_sample_data_ptr(const uint32_t idx)
{
    if (idx < NUMBER_OF_FILES) {
        return imgArrays[idx];
    }
    return NULL;
}

uint32_t get_sample_n_elements(void)
{
    return NUMBER_OF_FILES;
}

uint32_t get_sample_img_total_bytes()
{
    return IMAGE_DATA_SIZE;
}

uint32_t get_sample_img_width(void)
{
    return IMAGE_DATA_W;
}

uint32_t get_sample_img_height(void)
{
    return IMAGE_DATA_H;
}